INSERT ALL
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('2','MPO-Enlisting','অধ্যক্ষের অগ্রায়ন পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('3','MPO-Enlisting','১৫০ টাকার ননজুডিশিয়াল ষ্ট্যাম্পে সভাপতি ও প্রতিষ্ঠান প্রধান কর্তৃক প্রতিস্বাক্ষরে অঙ্গীকারনামা',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('4','MPO-Enlisting','একটি জাতীয় দৈনিক পত্রিকায় প্রচারিত নিয়োগ বিজ্ঞপ্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('5','MPO-Enlisting','একটি স্থানীয় দৈনিক পত্রিকায় প্রচারিত নিয়োগ বিজ্ঞপ্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('6','MPO-Enlisting','নিয়োগ সংক্রান্ত সকল রেজুলেশন কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('7','MPO-Enlisting','নিয়োগ পরীক্ষার ফলাফলশীট',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('8','MPO-Enlisting','শিক্ষাগত যোগ্যতার সকল সনদ পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('9','MPO-Enlisting','নিয়োগ পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('10','MPO-Enlisting','যোগদান পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('11','MPO-Enlisting','ডিজি’র প্রতিনিধি মনোনয়ন পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('12','MPO-Enlisting','প্রতিষ্ঠানের প্রথম ও শেষ এমপিও কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('13','MPO-Enlisting','ইনডেক্সধারী শিক্ষক হলে পূর্ববর্তী-প্রতিষ্ঠান/প্রতিষ্ঠান সমূহের সংশ্লিষ্ট শিক্ষক/কর্মচারীর ১ম ও শেষ এমপিও কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('14','MPO-Enlisting','নিবন্ধন সনদ পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('15','MPO-Enlisting','প্রতিষ্ঠানের স্বীকৃতি পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('16','MPO-Enlisting','ম্যানেজিং কমিটি অনুমোদনের কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('17','MPO-Enlisting','ইনডেক্সধারীর ক্ষেত্রে ব্যাংক প্রত্যয়ণপত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('18','MPO-Enlisting','ব্যাংক একাউন্ট খোলার প্রত্যয়ণপত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('19','MPO-Enlisting','প্রতিষ্ঠানের ভোকেশনাল শাখা খোলার মন্ত্রণালয়ের অনুমতি পত্র (জিও)',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('20','MPO-Enlisting','ট্রেড খোলার অনুমতি পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('21','MPO-Enlisting','ট্রেড অ্যাফিলিয়েশনের সর্বশেষ নবায়নের কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('22','MPO-TimeScale','সভাপতির মতামতসহ অগ্রায়ন পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('23','MPO-TimeScale','প্রধান শিক্ষক / সুপারিনটেনডেন্টের অগ্রায়ন পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('24','MPO-TimeScale','নিয়োগ পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('25','MPO-TimeScale','যোগদান পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('26','MPO-TimeScale','অভিজ্ঞতার সনদপত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('27','MPO-TimeScale','সকল শিক্ষাগত যোগ্যতার সনদ পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('28','MPO-TimeScale','আবেদনকারীর ১ম ও শেষ এমপিও কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('29','MPO-TimeScale','বর্তমান স্কেল প্রাপ্তির পর থেকে ৮ বছর পূর্ণ হয়েছে কিনা',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('30','MPO-TimeScale','টাইম স্কেল প্রাপ্যতার রেজুলেশন',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('31','MPO-NameCorrection','সভাপতির মতামতসহ অগ্রায়ন পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('32','MPO-NameCorrection','অধ্যক্ষের অগ্রায়ন পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('33','MPO-NameCorrection','নাম সংশোধনের রেজুলেশন',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('34','MPO-NameCorrection','এসএসসি’র সনদ পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('35','MPO-NameCorrection','ভুলের আগের এমপিও কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('36','MPO-BDateCorrection','সভাপতির মতামতসহ অগ্রায়ন পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('37','MPO-BDateCorrection','অধ্যক্ষের অগ্রায়ন পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('38','MPO-BDateCorrection','জন্ম তারিখ সংশোধনের রেজুলেশন',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('39','MPO-BDateCorrection','এসএসসি’র সনদ পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('40','MPO-BDateCorrection','ভুলের আগের এমপিও কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('41','MPO-BankCorrection','সভাপতির মতামতসহ অগ্রায়ন পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('42','MPO-BankCorrection','অধ্যক্ষের অগ্রায়ন পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('43','MPO-BankCorrection','ব্যাংক প্রত্যয়ণপত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('44','MPO-BankCorrection','ব্যাংক হিসাব নং সংশোধনের রেজুলেশন',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('45','MPO-IndexCorrection','সভাপতির মতামতসহ অগ্রায়ন পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('46','MPO-IndexCorrection','অধ্যক্ষের অগ্রায়ন পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('47','MPO-IndexCorrection','১ম এমপিও কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('48','MPO-IndexCorrection','ভুলের আগে এমপিও কপি',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('49','MPO-IndexCorrection','ইনডেক্স নম্বর সংশোধনের রেজুলেশন',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('50','MPO-IndexCorrection','নিয়োগ পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('51','MPO-IndexCorrection','যোগদান পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('52','MPO-IndexCorrection','নিয়োগ পরীক্ষার ফলাফলশীট',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('53','MPO-IndexCorrection','নিয়োগ বিজ্ঞপ্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('54','MPO-IndexCorrection','ইএম আইএস সেলের মতামত',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('55','MPO-NameCancellation','সভাপতির মতামতসহ অগ্রায়ন পত্',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('56','MPO-NameCancellation','অধ্যক্ষের অগ্রায়ন পত্র',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('57','MPO-NameCancellation','পদত্যাগ জনিত কারণে (পদত্যাগ জনিত নাম কর্তনের রেজুলেশন এবং পদত্যাগ পত্র )',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('58','MPO-NameCancellation','মৃত জনিত কারণে (পৌরসভা চেয়ারম্যান কর্তৃক মৃত্যু সনদ / মৃত্যু সার্টিফিকেট (ডাক্তার কর্তৃক), মৃত্যু  জনিত কারণে নাম কর্তনের রেজুলেশন )',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('59','MPO-NameCancellation','বহিস্কার জনিত কারণে ( সংশ্লিষ্ট বোর্ড কর্তৃক চূড়ান্ত বরখাস্ত পত্র এবং নাম কর্তনের জন্য রেজুলেশন)',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('60','MPO-ExClassOpen','অধ্যক্ষের মতামতসহ আবেদন',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('61','MPO-ExClassOpen','উপজেলা নির্বাহী অফিসারের হালনাগাদ পরিদর্শন প্রতিবেদন',SYSDATE,'1')
 INTO attachment_category (ID,APPLICATION_NAME,ATTACHMENT_NAME,DATE_CREATED,MODULE_ID) VALUES ('62','MPO-ExClassOpen','সংশ্লিষ্ট বোর্ড কর্তৃক বিদ্যালয় পরিদর্শক এর হালনাগাদ পরিদর্শন প্রতিবেদন',SYSDATE,'1')
SELECT * FROM dual;
