SELECT ID as ENTITY_ID, ID as EMPLOYEE_ID, 'Employee' as ENTITY_NAME, FULL_NAME as REQUEST_FROM,
('Father: ' ||FATHER_NAME || ',Mother:' || MOTHER_NAME) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Employee'||ID) as CUSTOM_ID
FROM HR_EMPLOYEE_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Spouse' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_SPOUSE_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Name: ' ||SPOUSE_NAME || ',Birth:' || BIRTH_DATE||', Gender: '||GENDER) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Spouse'||ID) as CUSTOM_ID
FROM HR_SPOUSE_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Nominee' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_NOMINEE_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Name: ' ||NOMINEE_NAME || ',Birth:' || BIRTH_DATE||', Gender: '||GENDER) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Nominee'||ID) as CUSTOM_ID
FROM HR_NOMINEE_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Children' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_CHILDREN_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Name: ' ||CHILDREN_NAME || ',Birth:' || DATE_OF_BIRTH||', Gender: '||GENDER) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Children'||ID) as CUSTOM_ID
FROM HR_EMP_CHILDREN_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Education' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EDUCATION_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Exam: ' ||EXAM_TITLE || ',Sub:' || MAJOR_SUBJECT||', Year: '||SESSION_YEAR) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Education'||ID) as CUSTOM_ID
FROM HR_EDUCATION_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Employment' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMPLOYMENT_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Ins: ' ||PRESENT_INSTITUTE || ',JDt:' || JOINING_DATE||', RegDt: '||REGULARIZATION_DATE) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Employment'||ID) as CUSTOM_ID
FROM HR_EMPLOYMENT_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Address' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_ADDRESS_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Type: ' ||ADDRESS_TYPE || ',Dist:' || DISTRICT||', Contact: '||CONTACT_NUMBER) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Address'||ID) as CUSTOM_ID
FROM HR_EMP_ADDRESS_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Award' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_AWARD_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Name: ' ||AWARD_NAME || ',Area:' || AWARD_AREA||', Date: '||AWARD_DATE) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Award'||ID) as CUSTOM_ID
FROM HR_EMP_AWARD_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'ForeignTour' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_FOREIGN_TOUR_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Purpose: ' ||PURPOSE || ',Country:' || COUNTRY_NAME||', From: '||FROM_DATE) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('ForeignTour'||ID) as CUSTOM_ID
FROM HR_EMP_FOREIGN_TOUR_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'OtherService' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_OTHER_SERVICE_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Comp: ' ||COMPANY_NAME || ',Serv:' || SERVICE_TYPE||', Post: '||POSITION) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('OtherService'||ID) as CUSTOM_ID
FROM HR_EMP_OTHER_SERVICE_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'PreGovtJob' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_PRE_GOVT_JOB_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Org: ' ||ORGANIZATION_NAME || ',Post:' || POST_NAME||', Date: '||FROM_DATE) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('PreGovtJob'||ID) as CUSTOM_ID
FROM HR_EMP_PRE_GOVT_JOB_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'ProfMember' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_PROF_MEMBER_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Org: ' ||ORGANIZATION_NAME || ',Number:' || MEMBERSHIP_NUMBER||', Date: '||MEMBERSHIP_DATE) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('ProfMember'||ID) as CUSTOM_ID
FROM HR_EMP_PROF_MEMBER_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Promotion' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_PROMOTION_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Inst: ' ||INSTITUTE_TO || ',Dept:' || DEPARTMENT_TO||', Desig: '||DESIGNATION_TO) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Promotion'||ID) as CUSTOM_ID
FROM HR_EMP_PROMOTION_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Publication' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_PUBLICATION_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('PubName: ' ||PUBLICATION_TITLE || ',Date:' || PUBLICATION_DATE) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Publication'||ID) as CUSTOM_ID
FROM HR_EMP_PUBLICATION_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'ServHistory' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_SERVICE_HISTORY.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('ServDt: ' ||SERVICE_DATE || ',GazDt:' || GAZETTED_DATE||', Encadr: '||ENCADREMENT_DATE) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('ServHistory'||ID) as CUSTOM_ID
FROM HR_EMP_SERVICE_HISTORY WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Training' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_TRAINING_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Inst: ' ||INSTITUTE_NAME || ',Course:' || COURSE_TITLE||', Date: '||DURATION_FROM) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Training'||ID) as CUSTOM_ID
FROM HR_EMP_TRAINING_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'Transfer' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_TRANSFER_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Loc: ' ||LOCATION_TO || ',Dept:' || DEPARTMENT_TO||', Desig: '||DESIGNATION) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('Transfer'||ID) as CUSTOM_ID
FROM HR_EMP_TRANSFER_INFO WHERE LOG_STATUS IN (2,3)
UNION
SELECT ID as ENTITY_ID, EMPLOYEE_INFO_ID as EMPLOYEE_ID, 'ActingDuty' as ENTITY_NAME, (SELECT FULL_NAME FROM HR_EMPLOYEE_INFO WHERE ID=HR_EMP_ACTING_DUTY_INFO.EMPLOYEE_INFO_ID) as REQUEST_FROM,
('Inst: ' ||TO_INSTITUTION || ',Dept:' || TO_DEPARTMENT||', Desig: '||DESIGNATION) as REQUEST_SUMMARY, UPDATE_DATE as REQUEST_DATE,
LOG_STATUS as LOG_STATUS, LOG_COMMENTS as LOG_COMMENTS, LOG_ID as LOG_ID, 0 as IS_SELECTED, ('ActingDuty'||ID) as CUSTOM_ID
FROM HR_EMP_ACTING_DUTY_INFO WHERE LOG_STATUS IN (2,3)

ORDER BY REQUEST_FROM
